---
knit: "bookdown::render_book"
title: "R برای دانشمندان داده به پارسی"
author: "Hadley Wickham and Garrett Grolemund"
translator:
  - رضا اسمعیل زاده
  - جواد طاعتی
# url: 'https\://r4ds.had.co.nz/'
github-repo: reza-esmaeel-zade/r4ds-parsi
site: bookdown::bookdown_site
documentclass: book
---

# خوش آمدید {.unnumbered}

این وب سایت ویرایش دوم "R for Data Science" است. این کتاب به شما می‌آموزد که چگونه علم داده را با R انجام دهید: شما یاد خواهید گرفت که چگونه داده های خود را به R وارد کنید، آن‌ها را به مفیدترین ساختار تبدیل کنید، آن‌ها را تغییر دهید و تجسم کنید.

در این کتاب، تمرینی از مهارت های علم داده را خواهید یافت. درست همانطور که یک شیمیدان می آموزد که چگونه لوله های آزمایش را تمیز کند و یک آزمایشگاه را مدیریت کند، شما نیز یاد خواهید گرفت که چگونه داده ها را تمیز کنید و نمودارها را ترسیم کنید و علاوه بر آن بسیاری چیزهای دیگر. اینها مهارت‌هایی هستند که به علم داده اجازه می‌دهند، و در اینجا بهترین روش‌ها را برای انجام هر یک از این کارها با R پیدا می‌کنید. یاد می‌گیرید که چگونه از گرامر گرافیک، [برنامه‌نویسی بهینه](https://fa.wikipedia.org/wiki/%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87%E2%80%8C%D9%86%D9%88%DB%8C%D8%B3%DB%8C_%D8%A7%D8%AF%DB%8C%D8%A8%D8%A7%D9%86%D9%87 "Literate programming")، و تحقیقات تکرارپذیر برای صرفه‌جویی در زمان استفاده کنید. همچنین یاد خواهید گرفت که چگونه منابع شناختی را برای تسهیل اکتشافات هنگام بحث، تجسم و کاوش داده ها مدیریت کنید.

# پیشگفتار چاپ دوم {.unnumbered}

به ویرایش دوم "R for Data Science" خوش آمدید! این یک بازسازی اساسی از ویرایش اول است، مطالبی را که دیگر فکر نمی‌کنیم مفید باشند، حذف می‌کند، مطالبی را اضافه می‌کند که آرزو می‌کنیم در نسخه اول گنجانده شود، و به طور کلی متن و کد را به‌روزرسانی می‌کند تا تغییرات در بهترین شیوه‌ها را منعکس کند. ما همچنین بسیار هیجان‌زده هستیم که به یکی از نویسندگان جدید خوش آمد می‌گوییم: Mine Çetinkaya-Rundel، یک مربی برجسته علم داده و یکی از همکارانمان در Posit (شرکتی که قبلاً با نام RStudio شناخته می‌شد).

خلاصه‌ای از بزرگترین تغییرات به شرح زیر است:

-   قسمت اول کتاب به «کل بازی» تغییر نام داده است. هدف این بخش این است که قبل از اینکه به جزئیات بپردازیم، جزئیات تقریبی «کل بازی» علم داده را به شما ارائه دهد.

-   بخش دوم کتاب «تجسم» است. این بخش به ابزارهای تجسم داده ها و بهترین شیوه ها پوشش کامل تری نسبت به نسخه اول می دهد. بهترین مکان برای دریافت تمام جزئیات هنوز کتاب ggplot2 است، اما اکنون R4DS بیشتر از مهمترین تکنیک ها را پوشش می دهد.

-   بخش سوم کتاب اکنون «تبدیل» نام دارد و فصل‌های جدیدی در مورد اعداد، بردارهای منطقی و مقادیر گمشده به آن اضافه شده است. اینها قبلاً بخشی از فصل تبدیل داده ها بودند، اما برای پوشش دادن همه جزئیات به فضای بسیار بیشتری نیاز داشتند.

-   قسمت چهارم کتاب «وارد کردن» نام دارد. این مجموعه‌ای از فصل‌های جدید است که فراتر از خواندن فایل‌های متنی مسطح، کار با صفحات گسترده، گرفتن داده‌ها از پایگاه‌های داده، کار با داده‌های بزرگ، مستطیل کردن (جدولی کردن) داده‌های سلسله‌مراتبی، و جمع‌آوری داده‌ها از وب‌سایت‌ها است.

-   بخش "برنامه" باقی مانده است، اما از بالا به پایین بازنویسی شده است تا بر مهم ترین بخش های نوشتن و تکرار تابع تمرکز کند. نوشتن توابع اکنون شامل جزئیاتی در مورد نحوه بسته بندی توابع مرتب و منظم (برخورد با چالش های ارزیابی مرتب) است، زیرا این کار در چند سال اخیر بسیار آسان تر و مهم تر شده است. ما یک فصل جدید در مورد توابع مهم پایه R اضافه کرده‌ایم که احتمالاً در آن کد R پیچیده مشاهده خواهید کرد.

-   قسمت مدلسازی حذف شده است. ما هرگز فضای کافی برای ارائه مدلسازی نداشتیم و اکنون منابع بسیار بهتری در دسترس است. ما به طور کلی استفاده از بسته‌ی tidymodels و مطالعه مدل‌سازی Tidy با R توسط Max Kuhn و Julia Silge را توصیه می‌کنیم.

-   بخش "ارتباط" باقی مانده است، اما به طور کامل به روز شده است تا به جای R Markdown از Quarto استفاده کند. این نسخه از کتاب در Quarto نوشته شده است، و به وضوح ابزار آینده است. (نسخه دوم کتاب از Quarto به جای bookdown استفاده کرده است، اما در این ترجمه از نسخه دوم همچنان از پکیج bookdown استفاده شده است)
